### ISSUE TITLE
Map: (Urgent for demo) Dont force axis through 0 if the term has an annotated display range

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#147] opened 2023-05-03 15:40 UTC
We are finding terms representing years being forced through 0. This is undesirable, and needs to be rectified prior to some imminent demos. 

Previously we introduced a rule that continuous axes must go through 0, and so somewhere there is some logic to find the min of things like 0, display range, range. This logic should be updated so that annotated display ranges have priority to 0, even if above 0.

**Comment by dmfalke** [comment] 2023-05-03 16:01
The study metadata changed at some point.

What used to be:
```json
{
  "distributionDefaults": {
    "displayRangeMin": 2012,
    "displayRangeMax": 2015
  }
}
```

is now:
```json
{
  "distributionDefaults": {
    "rangeMin": 2012,
    "rangeMax": 2015
  }
}
```

**Comment by dmfalke** [comment] 2023-05-03 16:06
Oh, no. I take that back! `rangeMin` and `rangeMax` have always been there.

**Comment by dmfalke** [comment] 2023-05-03 16:08
I think the issue is that `displayRangeMin` and `displayRangeMax` are not being populated

**Comment by moontrip** [comment] 2023-05-03 16:14
From my quick observation, the issue is that we set 0 as one of min: there is a condition but will need to look into it further.

**Comment by dmfalke** [comment] 2023-05-03 16:16
@moontrip I found a case that includes `displayRangeMin` and `displayRangeMax`:

Study: GEMS1A Case Control
Variable: Enrollment year

**Comment by moontrip** [comment] 2023-05-04 04:19
Hi @d-callan and @danicahelb, a fix is now merged into the main branch so it would be reflected when the site is updated. Some screenshots can be seen at https://github.com/VEuPathDB/web-monorepo/pull/150#issue-1694609625

**Comment by dmfalke** [comment] 2023-05-04 11:55
The issue isn't quite resolved (see https://github.com/VEuPathDB/web-monorepo/pull/150#issuecomment-1534530355). I'm reopening the issue.

**Closed** 2023-05-04 18:21 UTC

**Comment by moontrip** [comment] 2023-05-05 14:46
Hi @dmfalke & @d-callan 
First of all, thank you for updating the work @dmfalke. 
I am curious if it is okay for the cases where the displayMin does not exist. It is probably rare, but I could see that Amazonia ICEMR Brazil cohort has the edge case, and its histogram at Browse and Subset look like this. Dave also mentioned about a case https://github.com/VEuPathDB/web-monorepo/issues/147#issuecomment-1533306251. Fixing metadata is one option and the other one is to temporarily check both displayMin and rangeMin?

![Amazon ICEMR Braziil Cohort hostipalization year histogramfilter](https://user-images.githubusercontent.com/12802305/236489655-3073cb15-f9f7-460e-8442-ae57e55108cd.png)

**Comment by d-callan** [comment] 2023-05-05 14:58
If you see cases like this you should point them out to @danicahelb , bc we would need to annotate the term.
