### ISSUE TITLE
Bug: SAM legend and plot colors can be reversed, depending on how filters are added

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-monorepo#218] opened 2023-05-12 22:51 UTC
Looking at the WWARN data on SAM...

I first filtered `Genotype or haplotype assessed` = `pfcrt k76` to look at the wildtype. I got this plot, which looks good:
<img width="468" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/265b7478-8634-4602-bda5-eaaa4a0a1054">

I then went back to change my filters for `Genotype or haplotype assessed` and added `pfcrt 76t` so that i could compare the wildtype to the mutant. I got this plot, which had the colors of the legend and the plot switched:
<img width="468" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/19393540-19dd-4a2e-a27d-7f09aa3945ee">

I then cleared all filters and re-added filters for `Genotype or haplotype assessed` ...this time filtering both `pfcrt k76` and `pfcrt 76t` at the SAME time. I got this plot, which once again has the colors correct:
<img width="468" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/e7e26344-8b03-4c74-a5fa-623bae5ca619">

Please make sure the legend colors match to the appropriate line in the graph, regardless of how the filters are ordered, thanks!

**Comment by dmfalke** [comment] 2023-05-13 14:12
The issue is that the legend is ordered by subset count, while the variable’s vocabulary is ordered by filter configuration.

A solution is to augment the overlay variable such that its vocab is in the same order as the legend. I’m not yet sure where to do this. More investigation is needed.

**Comment by bobular** [comment] 2023-05-15 08:56
I think this may be fixed by https://github.com/VEuPathDB/web-monorepo/pull/217
I can't reproduce with SCORE S. mansoni but will double check with WWARN...

**Comment by dmfalke** [comment] 2023-05-15 11:04
I may have found a hack solution that involves modifying the `filters` array passed to the active plot. The array is modified such that the order of values is the same as the legend items produced by the `useMarkers` hook. I wasn’t able to test, as my internet went out last night. I’ll test in a little bit.

**Comment by chowington** [comment] 2023-05-24 22:56
This issue wasn't automatically closed by merging the above PR, but maybe it should have been?

**Comment by bobular** [comment] 2023-05-25 15:31
> This issue wasn't automatically closed by merging the above PR, but maybe it should have been?

Yes, thanks, will do!

**Closed by bobular** 2023-05-25 15:31 UTC
Labels: bug
