### ISSUE TITLE
Binned lineplot axis label work

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#942] opened 2024-03-15 19:50 UTC
Follow-on from #762 

              It looks like this is doable:

![image](https://github.com/VEuPathDB/web-monorepo/assets/365139/8f52b7e7-0d37-4f7c-ba67-471add614135)

There are two properties that need to be set:
- `layout.xaxis.tickvals` -- this should be the same as `data[0].x`
- `layout.xaxis.ticktext` -- this should be the same as `data[0].binLabel`

_Originally posted by @dmfalke in https://github.com/VEuPathDB/web-monorepo/issues/762#issuecomment-1998088494_

**Comment by danicahelb** [comment] 2024-03-15 21:51
closing this ticket as this solution is not ideal.

@d-callan thinks the issue is that plotly is expecting the wrong end of the bin to be inclusive, and will try that fix next week

**Closed by danicahelb** 2024-03-15 21:51 UTC
