### ISSUE TITLE
Map: Timeline + marginal histogram component

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#130] opened 2023-04-28 01:44 UTC
This is needed for the tick QO, deadline sept.

Current plan is to add a floating chart which is primarily a timeline (lineplot w temporal xaxis) with a marginal histogram. This ticket is to build the component, not the visualization. It likely requires building a new lineplot component in visx with the same specs as the existing plotly component, with the exception that it has a linked histogram sharing its xaxis. Mockups with the exact specs will be available soon.

**Comment by asizemore** [comment] 2023-04-28 10:50
duplicate of #96 ?

**Comment by d-callan** [comment] 2023-05-03 19:09
an ex of what were aiming for:

![timeline_specs](https://user-images.githubusercontent.com/53306535/236018165-457219dd-dada-4020-95d9-95cdab628849.png)


* the axis should be placed in between the line and histo
* histogram is upright
* both line and histo should be colored by overlay, the height of the histo reflects counts of non-NULL values for all variables relevant to the line plot
* Ideally, this will have a dedicated tooltip. if time doesnt allow that we can do the same as we did for line for now. ill make a separate ticket for the tooltip and reference it here.
* no need to consider semantic zoom

**Comment by d-callan** [comment] 2023-05-16 18:55
talking w @asizemore today, we realized itd make a lot of sense for the histo to be optional in the component and required for the visualization

**Comment by moontrip** [comment] 2023-05-23 18:19
I have tested something but I wonder if we can go for multiple plots with two y-axes (left and right) in a single figure using plotly, instead of separate two plots: attached a screenshot: didn't make a component but tested at Codepen. In this case, it would probably be faster to implement than Visx and an additional advantage is that we can use tooltip relatively easy as also shown in the screenshot: tooltip contents can be adjusted as we did for other Vizs. 

![two y-axis01](https://github.com/VEuPathDB/web-monorepo/assets/12802305/b8871a96-273a-4a25-9b44-bb3337f54d56)

I am also checking/learning Visx approach as well.

**Comment by moontrip** [comment] 2023-05-23 18:58
Thank you for your sharing your thought @d-callan. If so, as far as I understand, basically we need to make two separate plots, one is line/scatter and the other is histogram anyway. So what if we just use plotly to plot two such different types of plots at up and down?

**Comment by d-callan** [comment] 2023-05-23 20:44
We also need the histo to respond to the x-axis controls as well, without actually having an xaxis.

**Comment by moontrip** [comment] 2023-05-23 21:16
> @moontrip do you know if plotly allows having a tooltip that spans multiple plots? Eventually we'd want the tooltip to span both the line and histogram parts of this visualization

@asizemore From my understanding, it is not possible at plotly and I doubt that visx supports that functionality either. But I will check.

**Comment by dmfalke** [comment] 2023-05-23 23:41
> > @moontrip do you know if plotly allows having a tooltip that spans multiple plots? Eventually we'd want the tooltip to span both the line and histogram parts of this visualization
> 
> 
> 
> @asizemore From my knowledge, it is not possible at plotly but I will check this out. I doubt that visx supports that functionality either, but will see.

I'd be surprised if neither supports manually triggering tooltips. We might have to disable the default tooltip triggers and add our own mouse over events to trigger the tooltips in both plots.

I'm also curious if we have a spec for this component, yet. If not, the very first thing we should do is define the props interface, possibly as a small group.

**Comment by moontrip** [comment] 2023-05-24 02:31
> 

@asizemore & @dmfalke 
I have looked into plotly docs etc. and it seems that there is a way to do that in pure plotly.js: need to test it and will do that tomorrow. 
It is not that straightforward how to do such a thing in React manner, as experienced in previous implementations being similar to this case. But I may be able to figure it out, if we will go for plotly approach.

**Closed** 2023-06-17 01:00 UTC
