### ISSUE TITLE
Map - unwanted 400 error-producing `map-markers` requests during variable change (post refactor)

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#572] opened 2023-10-25 11:57 UTC
This bug is observed on the refactor branch: https://github.com/VEuPathDB/web-monorepo/pull/424

It could be solved before merge or after.  But definitely a b66 issue.

To reproduce

Megastudy
Donut map - switch between variables "insecticide" and "Plasmodium falciparum infection status"
Watch the network logs.

There is a 400 where the output entity changes first, and then when `useDistributionOverlayConfig` returns its payload, the correct `StandaloneMapMarkersRequestParams` are sent to the `map-markers` back end.

The solution would probably be to bundle the outputEntityId in with the `overlayConfigResult` but I'm open to other solutions.

**Comment by moontrip** [comment] 2023-12-18 18:37
@bobular I have examined this carefully, however, I cannot produce 400 error following your description (and others) at my local VM. It might have been fixed during other works. Can you please check it out?

**Comment by dmfalke** [comment] 2024-02-14 15:47
I can't reproduce this now, either. Closing.

**Closed by dmfalke** 2024-02-14 15:47 UTC
