### ISSUE TITLE
Mbio: ranked abundance box and scatter dissolve mass spec data

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#807] opened 2024-01-26 12:09 UTC
Found on qa today

Study: FARMM
Viz: Ranked abundance boxplot
Data: Mass Spectrometry
Method: Max

Error:
```
Cannot read properties of undefined (reading 'length')
    at Boxplot.tsx:122:67
    at Array.map (<anonymous>)
    at Boxplot.tsx:94:12
    at n (PlotlyPlot.tsx:438:24)
```

I originally assumed the data was empty but that's not the case. Maybe it's still missing something? Needs some investigation!
<img width="698" alt="Screen Shot 2024-01-26 at 6 40 15 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/11710234/5823b83c-bb17-4682-b32c-aca1f3e1a891">

Other clues:
- works fine for the same study with Data: Species and Method: Max
- Also errs for Data: Mass Spec and Method: Median.

UPDATE
Upon further investigation I think the names of the variables are messing things up. The response has the names:
<img width="402" alt="Screen Shot 2024-01-26 at 7 06 40 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/11710234/459fb5a7-25c5-4117-a197-9ae596cca825">

whereas by the time we send the data to the BoxPlot component it looks like
<img width="383" alt="Screen Shot 2024-01-26 at 7 08 42 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/11710234/61cae02d-08e6-4b24-b79c-a9c1b40d4526">
and all the values are undefined. I bet the names are getting changed and then there's a lookup somewhere that fails and that's how we get `undefined` for everything.

Turns out the ranked abundance scatterplot does something similar! Data comes in nicely from the backend but by the time it gets to the plot component it's gone!

**Comment by bobular** [comment] 2024-01-26 19:47
Having a look at this. Not taking the ticket yet though.

Changing the labels from variable_ID to variable's displayName is normal for ranked abundance boxplots. I don't think that's the issue.

**Comment by bobular** [comment] 2024-01-26 20:27
The problem is actually in the back end response.

In the taxon abundance case, the labels in the series data are:
```
{
	"label": [
		"EUPATH_0009253_Bacteria_Actinobacteria_Actinobacteria",
		"EUPATH_0009253_Bacteria_Actinobacteria_Coriobacteriia",
		"EUPATH_0009253_Bacteria_Bacteroidetes_Bacteroidia",
		"EUPATH_0009253_Bacteria_Firmicutes_Bacilli",
		"EUPATH_0009253_Bacteria_Firmicutes_Clostridia",
		"EUPATH_0009253_Bacteria_Firmicutes_Erysipelotrichia",
		"EUPATH_0009253_Bacteria_Firmicutes_Firmicutes_unclassified",
		"EUPATH_0009253_Bacteria_Firmicutes_Negativicutes",
		"EUPATH_0009253_Bacteria_Proteobacteria_Betaproteobacteria",
		"EUPATH_0009253_Bacteria_Proteobacteria_Gammaproteobacteria"
	]
}
```
and the labels in the `boxplot.data.config.variables...vocabulary` are the same.

However, in the metabolomics case, the data series labels are 
```
{
	"label": [
		"C18_2_LPC_HIL_pos",
		"C34_2_PC_C8_pos",
		"C36_2_PC_C8_pos",
		"C36_3_PC_C8_pos",
		"caprylate_HIL_neg",
		"citrate_isocitrate_HIL_neg",
		"fructose_glucose_galactose_HIL_neg",
		"hippurate_HIL_neg",
		"inositol_HIL_neg",
		"lactate_HIL_neg"
	]
}
```
and the computed metadata vocabulary is
```
{
	"vocabulary": [
		"OBI_0000470_C36_3_PC_C8_pos",
		"OBI_0000470_caprylate_HIL_neg",
		"OBI_0000470_citrate_isocitrate_HIL_neg",
		"OBI_0000470_fructose_glucose_galactose_HIL_neg",
		"OBI_0000470_lactate_HIL_neg",
		"OBI_0000470_C34_2_PC_C8_pos",
		"OBI_0000470_inositol_HIL_neg",
		"OBI_0000470_C36_2_PC_C8_pos",
		"OBI_0000470_hippurate_HIL_neg",
		"OBI_0000470_C18_2_LPC_HIL_pos"
	]
}
```

When these don't match, `BoxplotVisualization` doesn't like it!

Is the data service perhaps detecting an underscore and deciding it doesn't need to prefix with the `OBI_0000470_`?

@asizemore

**Comment by d-callan** [comment] 2024-01-29 11:42
Can someone confirm the declared vocabulary for that variable actually represents real values seen in the dataset? I suspect a data loading issue.

**Comment by asizemore** [comment] 2024-01-29 12:56
@d-callan i dont follow what you mean by "declared vocabulary". The "vocabulary" here should be a list of variables because it's part of a collection

**Comment by d-callan** [comment] 2024-01-29 14:32
lol yea. helps to read the whole ticket i suppose.. if its affecting both box and scatter, and only vizs w collections, and the config looks right but not the data, id think the only place can be the abstract/ parent plot.data class. 

AND.... i just went to look quickly at it and oddly enough think i saw it basically immediately. i made and merged a minor change just now.

**Closed by d-callan** 2024-01-29 14:32 UTC
Labels: bug

**Comment by asizemore** [comment] 2024-01-29 16:31
Awesome thanks @d-callan !
