### ISSUE TITLE
eda : viz tab: clanky ux issue

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#840] opened 2024-02-12 13:38 UTC
i think the icon on the right side should do the same as when clicking on the visualize tab. 
<img width="1269" alt="Screen Shot 2024-02-12 at 8 36 15 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/e359be7a-62bf-4c5c-a2e6-ddb8ac44dbef">

**Comment by jernestmyers** [comment] 2024-02-12 14:20
It still does on the live site. I recall implementing that logic.

This is a regression, possibly caused by https://github.com/VEuPathDB/web-monorepo/pull/831

**Comment by jernestmyers** [comment] 2024-02-12 14:34
After more digging, I realize the changes from #831 have not been built into the QA sites, so it's very likely that this issue is resolved.

**Comment by jernestmyers** [comment] 2024-02-14 15:20
Resolved by #831

**Closed by jernestmyers** 2024-02-14 15:20 UTC
